version: '3'
services:
  mongo:
    image: 'mongo'
    ports:
    - 27017:27017

  api:
    build: .
    command: "npm run start:dev"
    env_file: .env
    volumes:
      - "./:/home/node/app"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
